### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by cdinouard** [WasiqB/multiple-cucumber-html-reporter#299]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 3.4.0
 - Node.js version: 18.18.2
 - NPM version: 8.19.4 
 - Platform name and version: MacOS Monterey
 - Cucumber version: 9.6.0

**Config of multiple-cucumber-html-reporter**
<img width="298" alt="image" src="https://github.com/WasiqB/multiple-cucumber-html-reporter/assets/146357786/4a9a6056-a1ae-4551-9bb2-aebf94c4b9b0">

**Describe the bug**
In the Show error of a failing step, error message is encoded
![image](https://github.com/WasiqB/multiple-cucumber-html-reporter/assets/146357786/dbc81e9c-8647-43f7-9a46-296f27ef9a85)

**To Reproduce**
Steps to reproduce the behavior: just run a test that is failing and open Show error

**Expected behavior**
A readable text error 

Thank you for your help

**Comment by animeshkumar29** [comment]
It will be great if you solve this Issue, i am also facing same issue , and its really hard to See what Error in report

**Comment by cdinouard** [comment]
I found a solution, I put "FORCE_COLOR=0" in the script part in the package.json file (where you put the command to run your tests), hope it will work for you too

**Comment by animeshkumar29** [comment]
Thanks a Lot for Quick reply 
i am using Like this in my Package.json under scripts 
 `"scripts": {
 "local": "cucumber-js --tags=@SysCoreProfile || true && npm run posttest",
 }`
 Where i can append ?
