### ISSUE TITLE
Screenshots are not attached to HTML report

### ISSUE THREAD

**Issue by KimberlingYarihuaman** [WasiqB/multiple-cucumber-html-reporter#382]
# **Environment**:

- Node.js version: [v20.17.0]
- Cypress: [v13.14.1]
- multiple-cucumber-html-reporter: [v3.7.0]
- cypress-cucumber-preprocessor: [v4.3.1]

## Config of multiple-cucumber-html-reporter

I´ve configured the report so that to be generated from cucumberJson with multiple-cucumber-html-reporter

![Captura de pantalla 2024-09-17 111128](https://github.com/user-attachments/assets/1b8b33a8-94d4-4910-8bfa-f769f850c61e)

![Captura de pantalla 2024-09-17 110933](https://github.com/user-attachments/assets/25329cc7-9915-4938-9454-c4c10bd2e5c8)

![Captura de pantalla 2024-09-17 111708](https://github.com/user-attachments/assets/c3fb4cb4-7256-403c-ac54-7f1c9fa98550)

Also, I´ve tried using [cypress-cucumber-attach-screenshots-to-failed-steps](https://www.npmjs.com/package/cypress-cucumber-attach-screenshots-to-failed-steps) with the report, but I´ve gotten the same.

## Describe the bug

The report is not getting attached the screenshots, only shows the error.

![Captura de pantalla 2024-09-17 104158](https://github.com/user-attachments/assets/c83bd57e-b855-4ab7-8251-644757d4779f)

## Expected behavior

The report should get attached the screenshots.

**Comment by Sven-Seyfert** [comment]
Hi @KimberlingYarihuaman 👋 ,

how does you TakeScreenshot function look like in Cypress and when should it fire?
I mean, in WebdriverIO, Seleninum etc. you usually have to setup a hook like Before, After, to call the specific Screenshot function. I guess this is very similar what you have to do with Cypress, am I right?

Did you do this? Get us a bit more code to work with. My feeling tells me it's not a issues of the report.

Best regards
Sven

**Comment by Sven-Seyfert** [comment]
Like in the [cypress docs](https://docs.cypress.io/guides/guides/screenshots-and-videos#Screenshots) described, the screenshots will be stored in `cypress/screenshots` folder which is maybe not recognised by the reporter 🤔 ?

Do you use `cypress run` or `cypress open`?

> Additionally, Cypress will automatically capture screenshots when a failure happens during cypress run. Screenshots on failure are not automatically taken during cypress open.

My guess is: you have to define the location to the screenshots.

Best regards
Sven

**Comment by KimberlingYarihuaman** [comment]
Hi @Sven-Seyfert !

I´m running the tests with `cypress run` and the folder `cypress/screenshots` are being created, but the report keeps without showing the screenshots. Also, I defined the path for the screenshots (in cucumberReport.js) but I got the same result.

Regards

**Comment by Sven-Seyfert** [comment]
Okay, sad. Without a reproducible example, I cannot further support you.
Could you provide a small running cypress project which we could execute and maybe debug?

**Comment by KimberlingYarihuaman** [comment]
Yes @Sven-Seyfert let me to do a small example and I will attach in this question.
Thanks

**Comment by KimberlingYarihuaman** [comment]
Hi @Sven-Seyfert !

I attached a small example where you will be able to reproduce the issue. You should read the README.md file to understand how to run the tests and generate the report.

[cypress-tests-ok.zip](https://github.com/user-attachments/files/17171166/cypress-tests-ok.zip)

Thanks in advance

Regards.

**Comment by KimberlingYarihuaman** [comment]
Hi!

I solved this issues chaging the lib **cypress-cucumber-preprocessor** to **@badeball/cypress-cucumber-preprocessor**. Additional, added the following configuration into **package.json** , and from it generate the report with **multiple-cucumber-html-reporter** . It allows .json file to store images and they´ll show in the report.


**_Package.json:_**

```
 "cypress-cucumber-preprocessor": {
    "html": {
      "enabled": false,
      "output": "path-for-html-report"
    },
    "json": {
      "enabled": true,
      "output": "path-for-jsons-file"
    },
    "nonGlobalStepDefinitions": true
  },
```

**Comment by KimberlingYarihuaman** [comment]
Hi!

I solved this issues chaging the lib **cypress-cucumber-preprocessor** to **@badeball/cypress-cucumber-preprocessor**. Additional, added the following configuration into **package.json** , and from it generates the report with **multiple-cucumber-html-reporter** . It allows .json file to store images and they´ll show in the report.


**_Package.json:_**

```
 "cypress-cucumber-preprocessor": {
    "html": {
      "enabled": false,
      "output": "path-for-html-report"
    },
    "json": {
      "enabled": true,
      "output": "path-for-jsons-file"
    },
    "nonGlobalStepDefinitions": true
  },
```
